-- Apply this migration before deploying with spring.jpa.hibernate.ddl-auto=validate.
-- Existing users must provide a mobile number before it can be marked NOT NULL.

ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(16);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_mobile_number ON users (mobile_number);

CREATE TABLE IF NOT EXISTS password_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    otp_hash VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0
);

-- After collecting mobile numbers for pre-existing accounts, enforce the model constraint:
-- ALTER TABLE users ALTER COLUMN mobile_number SET NOT NULL;
